blank_issues_enabled: true
contact_links:
  - name: 🌐 Support utilisateur TwinLens
    url: https://twinlens.devitek.fr/support.html
    about: Pour l'aide à l'utilisation (pas un bug), passe par la page support.
